<DefaultLayout@BoxLayout>:
    padding: '50dp', '50dp', '50dp', '20dp'
    orientation: 'vertical'
    spacing: '30dp'

<TitleLabel@Label>:
    size_hint: 0.8, None
    pos_hint: {"center_x": 0.5}
    height: "50dp"
    font_size: '45dp'
    color: (0,0,0,1)

<MyButton@Button>:
    size_hint: 0.8, None
    pos_hint: {"center_x": 0.5}
    height: "60dp"

<LineTextInput@TextInput>
    multiline: False
    font_size: '20dp'
    # halign: "center"